<a href="https://colab.research.google.com/github/rikurzt/Finacial_analyze_course_HW/blob/main/%E9%87%91%E8%9E%8D_6%E5%A4%A7%E6%95%B8%E6%93%9A_HW1_7113029027%E6%9D%8E%E5%86%A0%E5%BB%B7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#證交所API

In [54]:
import pandas as pd
import requests
import json
from datetime import datetime

In [59]:
def call_twse_api(id,data=None, headers=None):
  today = datetime.today().strftime('%Y%m%d')
  stock_id = id
  url="https://www.twse.com.tw/rwd/zh/afterTrading/STOCK_DAY?date={today}&stockNo={stock_id}&response=json".format(today=today, stock_id=stock_id)

  try:
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    return response

  except requests.exceptions.RequestException as e:
    print(f"Error calling API: {e}")
    return None

In [92]:
respond = call_twse_api("0050")
respond.json()['data']

[['113/09/02',
  '8,406,621',
  '1,522,822,665',
  '181.90',
  '182.45',
  '180.50',
  '180.85',
  '-0.50',
  '11,557'],
 ['113/09/03',
  '9,951,882',
  '1,796,839,463',
  '181.00',
  '181.50',
  '179.70',
  '180.05',
  '-0.80',
  '10,334'],
 ['113/09/04',
  '34,040,370',
  '5,856,531,211',
  '171.00',
  '173.80',
  '170.00',
  '171.25',
  '-8.80',
  '76,198'],
 ['113/09/05',
  '9,617,832',
  '1,667,185,291',
  '172.85',
  '174.65',
  '171.75',
  '172.30',
  '+1.05',
  '19,940'],
 ['113/09/06',
  '8,941,475',
  '1,556,560,053',
  '173.00',
  '174.90',
  '171.85',
  '174.75',
  '+2.45',
  '13,003'],
 ['113/09/09',
  '16,353,482',
  '2,796,547,163',
  '170.40',
  '172.10',
  '170.30',
  '172.05',
  '-2.70',
  '27,362'],
 ['113/09/10',
  '9,866,281',
  '1,698,214,149',
  '173.40',
  '173.40',
  '171.15',
  '172.35',
  '+0.30',
  '16,346'],
 ['113/09/11',
  '5,427,964',
  '933,696,240',
  '172.35',
  '172.50',
  '171.50',
  '171.85',
  '-0.50',
  '11,868'],
 ['113/09/12',
  '16,337,565',
  '2,900,529,886',
  '176.10',
  '178.65',
  '176.10',
  '178.30',
  '+6.45',
  '15,442'],
 ['113/09/13',
  '4,775,976',
  '852,453,956',
  '179.00',
  '179.35',
  '177.85',
  '178.40',
  '+0.10',
  '8,283'],
 ['113/09/16',
  '6,206,362',
  '1,109,655,765',
  '178.60',
  '179.20',
  '178.30',
  '178.75',
  '+0.35',
  '11,707'],
 ['113/09/18',
  '9,649,985',
  '1,713,884,250',
  '178.50',
  '179.10',
  '176.55',
  '177.85',
  '-0.90',
  '14,610'],
 ['113/09/19',
  '8,553,792',
  '1,532,937,205',
  '178.00',
  '180.20',
  '177.00',
  '180.15',
  '+2.30',
  '10,740']]

In [100]:
df = pd.DataFrame(respond.json().get('data'))
df.columns = respond.json().get('fields')
df

,日期,成交股數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,成交筆數
0,113/09/02,"8,406,621","1,522,822,665",181.90,182.45,180.50,180.85,-0.50,"11,557"
1,113/09/03,"9,951,882","1,796,839,463",181.00,181.50,179.70,180.05,-0.80,"10,334"
2,113/09/04,"34,040,370","5,856,531,211",171.00,173.80,170.00,171.25,-8.80,"76,198"
3,113/09/05,"9,617,832","1,667,185,291",172.85,174.65,171.75,172.30,+1.05,"19,940"
4,113/09/06,"8,941,475","1,556,560,053",173.00,174.90,171.85,174.75,+2.45,"13,003"
5,113/09/09,"16,353,482","2,796,547,163",170.40,172.10,170.30,172.05,-2.70,"27,362"
6,113/09/10,"9,866,281","1,698,214,149",173.40,173.40,171.15,172.35,+0.30,"16,346"
7,113/09/11,"5,427,964","933,696,240",172.35,172.50,171.50,171.85,-0.50,"11,868"
8,113/09/12,"16,337,565","2,900,529,886",176.10,178.65,176.10,178.30,+6.45,"15,442"
9,113/09/13,"4,775,976","852,453,956",179.00,179.35,177.85,178.40,+0.10,"8,283"
10,113/09/16,"6,206,362","1,109,655,765",178.60,179.20,178.30,178.75,+0.35,"11,707"
11,113/09/18,"9,649,985","1,713,884,250",178.50,179.10,176.55,177.85,-0.90,"14,610"
12,113/09/19,"8,553,792","1,532,937,205",178.00,180.20,177.00,180.15,+2.30,"10,740"

# Yahoo爬蟲

In [98]:
from bs4 import BeautifulSoup

In [136]:
stock_id = "2330"
url = "https://tw.stock.yahoo.com/quote/{stock_id}.TW".format(stock_id=stock_id)
response = requests.get(url)
html_content = response.text

In [138]:
soup = BeautifulSoup(html_content, 'html.parser')

In [139]:
table = soup.find('div', {'class': 'Fx(n) W(316px) Bxz(bb) Pstart(16px) Pt(12px)'})
rows = table.find_all('li')


data = []

for row in rows:
    cells_col = row.find_all('span')
    data.append([cell.text.strip() for cell in cells_col])

data = list(zip(*data))
data

[('成交',
  '開盤',
  '最高',
  '最低',
  '均價',
  '成交金額(億)',
  '昨收',
  '漲跌幅',
  '漲跌',
  '總量',
  '昨量',
  '振幅'),
 ('960',
  '940',
  '960',
  '936',
  '949',
  '310.27',
  '941',
  '2.02%',
  '19.00',
  '32,674',
  '28,394',
  '2.55%')]

In [135]:
df = pd.DataFrame(data[1:], columns=data[0])
df

    成交   開盤   最高   最低   均價 成交金額(億)   昨收    漲跌幅     漲跌      總量      昨量     振幅
0  960  940  960  936  949  310.27  941  2.02%  19.00  32,674  28,394  2.55%

## 取得月報表

In [151]:
stock_id = "2330"
url = "https://tw.stock.yahoo.com/quote/{stock_id}.TW/income-statement".format(stock_id=stock_id)
response = requests.get(url)
html_content = response.text

In [177]:
soup = BeautifulSoup(html_content, 'html.parser')

In [196]:
table = soup.find('div', {'class': 'Pos(r) Ov(h)'})
header = table.find('div', {'class': 'table-header Ovx(s) Ovy(h) W(100%)'})
rows = table.find('div', {'class': 'table-body-wrapper'})

data = []



for row in rows.find_all('li'):
    cells_col = row.find_all('span')
    data.append([cell.text.strip() for cell in cells_col])

[['營業收入',
  '673,510,177',
  '592,644,201',
  '625,528,856',
  '546,732,758',
  '480,841,254',
  '508,632,973',
  '625,531,868',
  '613,142,743',
  '534,140,808',
  '491,075,873',
  '438,189,306',
  '414,670,379',
  '372,145,122',
  '362,410,230',
  '361,533,057',
  '356,426,204',
  '310,698,367',
  '310,597,183',
  '317,237,065',
  '293,045,439'],
 ['營業毛利',
  '358,124,478',
  '314,505,269',
  '331,767,925',
  '296,642,464',
  '260,199,847',
  '286,500,392',
  '389,184,929',
  '370,498,717',
  '315,467,994',
  '273,203,166',
  '230,679,228',
  '212,848,684',
  '186,234,135',
  '189,775,219',
  '195,188,826',
  '190,480,670',
  '164,692,825',
  '160,784,181',
  '159,240,985',
  '139,432,161'],
 ['營業費用',
  '70,295,310',
  '65,357,281',
  '71,621,021',
  '68,708,791',
  '58,194,560',
  '55,309,344',
  '64,535,382',
  '60,186,462',
  '53,374,518',
  '48,611,190',
  '47,877,762',
  '41,649,916',
  '40,583,423',
  '39,111,833',
  '38,321,439',
  '40,891,355',
  '33,520,709',
  '32,323,046',
  '34,942,621',
  '31,378,953'],
 ['營業利益',
  '286,555,542',
  '249,018,306',
  '260,204,503',
  '228,064,903',
  '201,958,043',
  '231,238,157',
  '325,040,770',
  '310,324,214',
  '262,123,749',
  '223,790,118',
  '182,771,954',
  '171,003,548',
  '145,667,205',
  '150,538,190',
  '157,120,174',
  '150,047,349',
  '131,094,538',
  '128,521,637',
  '124,243,722',
  '107,887,292'],
 ['稅後淨利',
  '247,661,438',
  '225,221,263',
  '238,306,201',
  '210,795,274',
  '181,717,006',
  '206,949,036',
  '295,878,482',
  '280,968,407',
  '237,180,252',
  '202,873,374',
  '166,373,515',
  '156,479,154',
  '134,481,716',
  '139,738,749',
  '142,824,524',
  '137,378,151',
  '120,892,514',
  '117,062,893',
  '116,078,194',
  '101,102,454']]

In [198]:
df = pd.DataFrame(data, columns=header.text.split())
df

,年度/月份2024,Q22024,Q12023,Q42023,Q32023,Q22023,Q12022,Q42022,Q32022,Q22022,...,Q42021,Q32021,Q22021,Q12020,Q42020,Q32020,Q22020,Q12019,Q42019,Q3
0,營業收入,"673,510,177","592,644,201","625,528,856","546,732,758","480,841,254","508,632,973","625,531,868","613,142,743","534,140,808",...,"438,189,306","414,670,379","372,145,122","362,410,230","361,533,057","356,426,204","310,698,367","310,597,183","317,237,065","293,045,439"
1,營業毛利,"358,124,478","314,505,269","331,767,925","296,642,464","260,199,847","286,500,392","389,184,929","370,498,717","315,467,994",...,"230,679,228","212,848,684","186,234,135","189,775,219","195,188,826","190,480,670","164,692,825","160,784,181","159,240,985","139,432,161"
2,營業費用,"70,295,310","65,357,281","71,621,021","68,708,791","58,194,560","55,309,344","64,535,382","60,186,462","53,374,518",...,"47,877,762","41,649,916","40,583,423","39,111,833","38,321,439","40,891,355","33,520,709","32,323,046","34,942,621","31,378,953"
3,營業利益,"286,555,542","249,018,306","260,204,503","228,064,903","201,958,043","231,238,157","325,040,770","310,324,214","262,123,749",...,"182,771,954","171,003,548","145,667,205","150,538,190","157,120,174","150,047,349","131,094,538","128,521,637","124,243,722","107,887,292"
4,稅後淨利,"247,661,438","225,221,263","238,306,201","210,795,274","181,717,006","206,949,036","295,878,482","280,968,407","237,180,252",...,"166,373,515","156,479,154","134,481,716","139,738,749","142,824,524","137,378,151","120,892,514","117,062,893","116,078,194","101,102,454"